server:
  port: 8080
  servlet:
    context-path: /project-archetype


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.demo.pojo
  mapperLocations: classpath:mappers/*.xml