server:
  port: 8080
  servlet:
    context-path: /project-archetype

mybatis:
  mapperLocations: classpath:mappers/*.xml
  configuration:
    cache-enabled: false # mybatis 是否开启全局二级缓存


logging:
  level:
    wr1ttenyu:
      f1nal:
        study:
          project:
            archetype:
              dao:
               UUserMapper: debug

spring:
  datasource:
    url: jdbc:mysql://122.51.219.124:3306/wr1ttenyu
    username: root
    password: p@ssword
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
    # Redis数据库索引（默认为0）TODO REDIS 数据库索引的作用
#    database: 0
#    host: 122.51.219.124
#    port: 6379
#    password: A@awr1ttenyu
#    timeout: PT1000S